name: GitHub Actions CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install tox
        run: python3 -m pip install tox
      - name: run tox
        run: python3 -m tox
